name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Rust Nightly
      run: rustup update nightly && rustup default nightly
    - name: Build
      run: cargo build -r --verbose
    - name: Run tests
      run: cargo test -r --verbose
    - name: Run solutions
      run: cargo run -r --verbose
